### PR TITLE
Fix : Change in the title of alert box

### LINKED ISSUE #22: Change in the title of alert box
**I'm submitting a ...**

- [x] bug report
- [ ] feature request

**Current behavior:**

The "SearchByACode" alertbox, shows title "Type Your Message"

**Expected behavior:**

The "SearchByACode" alertbox,  title should be "Enter your ACode"

**Steps to reproduce:**
Open Addy application -> Click on "SearchByACode" button

### PR DESCRIPTION
**Pull request by GOVINDDIXIT**
#### Checklist

- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)

**Changes proposed in this pull request**
-
-
-

**Screenshots (if appropriate)**

**Link to live demo (if appropriate):**

Fixes #22

### CODE REVIEW

**Comment by GOVINDDIXIT** [comment]
I had updated the alertbox as demanded in the issue #22 but need help why I am getting The Travis CI build failed

**Comment by GOVINDDIXIT** [comment]
capture

**Comment by yashovardhanagrawal** [comment]
Add label `Merge Blocked` as CI is failing, @reverie-ss you can still review it to completion but wait for the CI to be fixed before you merge it

**Comment by yashovardhanagrawal** [comment]
@GOVINDDIXIT this PR is currently not acceptable as you haven't been assigned the issue
follow the steps first

**Comment by GOVINDDIXIT** [comment]
I had made an account on Gitter but how to proceed further

**Comment by GOVINDDIXIT** [comment]
@reverie-ss  What more I have do with this PR in order to get merged

**Comment by reverie-ss** [comment]
@GOVINDDIXIT 
Please complete the PR description properly. It would then be easy to convey your work to us.
The CI needs to be fixed first! Let me look into it.

**Comment by GOVINDDIXIT** [comment]
I will create another PR

**Pull request closed without merging**
